Update in faq
typegoose/typegoose pull request #394
Opened 2020-09-29 16:08 UTC by Zony-Zhao

## Related Issues

- #1

2020-09-29 16:36 UTC, hasezoey requested changes

2020-09-29 16:36 UTC, hasezoey commented on docs/guides/faq.md
> +# For Edge Cases
```suggestion
## For Edge Cases
```

2020-09-29 16:36 UTC, hasezoey commented on docs/guides/faq.md
> +```
````suggestion
```ts
````

2020-09-29 17:23 UTC, VottusCode requested changes

2020-09-29 17:23 UTC, VottusCode commented on docs/guides/faq.md
> +class Cat{
```suggestion
class Cat {
```

2020-09-29 17:23 UTC, VottusCode commented on docs/guides/faq.md
> +since mongoose would auto generate virtual 'id' for '_id', and a '_id' when saving.
```suggestion
without any decorators. Mongoose will auto generate virtual 'id' for '_id', and a '_id' when saving.
```

2020-12-04 11:12 UTC, hasezoey approved these changes

2020-12-04 11:17 UTC, merged