feat(getModelForClass): use customName and automaticName from options (#495)
typegoose/typegoose pull request #502
Opened 2021-03-05 17:39 UTC by schdck

This PR adds an customOptions optional field to `getName`. The function will priorize `options.customName`, `options.automaticName` and `schemaOptions.collection` provided in `customOptions` over the ones extracted via Reflection.

With this, `getModelForClass` can send the options it receveid to `getName`, fixing the issue where those fields, when provided via options to `getModelForClass` were not taken into account.

## Related Issues

fixes #495

2021-03-05 19:01 UTC, hasezoey requested changes
please add tests
(also for working with `getClass`)

2021-03-05 23:07 UTC, schdck commented
Is this enough? I don't understand what you mean by "also for working with getClass". Thanks.

2021-03-06 09:02 UTC, hasezoey commented
sorry if this wasnt clear, i meant to add tests and check if its compatible with

2021-03-06 16:01 UTC, schdck commented
No problem! 😄 I see what you mean now. 

Added two tests covering `getClass` when sending `customName` or `automaticName` via options to `getModelForClass`. It works as long as the user knows the generated model name.

Let me know if there's any other way I can improve the PR!

2021-03-08 09:34 UTC, hasezoey commented
@schdck are you ok with the changes made?

2021-03-08 14:54 UTC, schdck commented
Yep, they seem fine @hasezoey! Great job!

2021-03-08 15:18 UTC, merged

2022-05-28 20:35 UTC, hasezoey commented
@schdck was there a specific reason why `options` and `overwriteOptions` in `buildSchema`(`typegoose.ts`) were split and not just one option? (because `IModelOptions` includes a `schemaOptions`)